# Generated by Django 5.0.1 on 2024-01-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstore_firaas_modules_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('redirect', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_clients_created_by', to='bookstore_firaas_modules_admin.admin')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_clients_updated_by', to='bookstore_firaas_modules_admin.admin')),
            ],
            options={
                'db_table': 'oauth_clients',
            },
        ),
        migrations.CreateModel(
            name='OauthAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.TextField()),
                ('scope', models.CharField(max_length=255)),
                ('expired_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('oauth_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_access_tokens_created_by', to='oauth.oauthclient')),
            ],
            options={
                'db_table': 'oauth_access_tokens',
            },
        ),
        migrations.CreateModel(
            name='OauthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.TextField()),
                ('expired_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('oauth_access_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_access_tokens_created_by', to='oauth.oauthaccesstoken')),
            ],
            options={
                'db_table': 'oauth_refresh_tokens',
            },
        ),
    ]
