# Generated by Django 5.0.1 on 2024-01-08 20:35

import bookstore_firaas.utils.upload
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstore_firaas_modules_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=functools.partial(bookstore_firaas.utils.upload._update_filename, *(), **{'path': 'products/'}))),
                ('video', models.FileField(upload_to=functools.partial(bookstore_firaas.utils.upload._update_filename, *(), **{'path': 'products/'}))),
                ('description', models.CharField(max_length=255)),
                ('is_highlighted', models.BooleanField()),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created_by', to='bookstore_firaas_modules_admin.admin')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated_by', to='bookstore_firaas_modules_admin.admin')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
